name: Streamlit Application

# Step2: From which branch you want to execute
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read # now push it to GitHub. Usually, it will fail in GitHub because there is nothing to execute

# Step3: Assign some jobs
jobs:
  build:
    runs-on: ubuntu-latest # when we join with EC2 instance we need to replace it with [self-hosted]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12" # now push everything to GitHub to install Python in GitHub
      
        #step4: installation requirments.txt in another segment
      - name: install Dependencies
        run: | #if we need to run multiple commands then we use this symbol. flake8 and pytest is used for unit testing(eg:if code is in github and whenever we are pushing we use it)#
          python -m pip install --upgrade pip
          pip install flake8 pytest 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # -f is force & "fi" is reverse of "if" which will close the loop. Now push it to github for install to begin.